/*
 * Generated by dtrace(1M).
 */

#pragma once

namespace Changjiang {

#ifdef __cplusplus
extern "C" {
#endif

#if _DTRACE_VERSION

#define CHANGJIANG_CLOSE() __dtrace_changjiang___close()
#define CHANGJIANG_CLOSE_ENABLED() __dtraceenabled_changjiang___close()
#define CHANGJIANG_OPEN() __dtrace_changjiang___open()
#define CHANGJIANG_OPEN_ENABLED() __dtraceenabled_changjiang___open()

extern void __dtrace_changjiang___close(void);
extern int __dtraceenabled_changjiang___close(void);
extern void __dtrace_changjiang___open(void);
extern int __dtraceenabled_changjiang___open(void);

#else

#define CHANGJIANG_CLOSE()
#define CHANGJIANG_CLOSE_ENABLED() (0)
#define CHANGJIANG_OPEN()
#define CHANGJIANG_OPEN_ENABLED() (0)

#endif

#ifdef __cplusplus
}
#endif

}  // namespace Changjiang
